<template>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
  <div>我是首页</div>
</template>

<script setup></script>

<style scoped lang="less"></style>
